# 消息
CELERY_TIMEZONE = 'Asia/Shanghai'
CELERY_MESSAGE_COMPRESSION = "gzip"
CELERY_TASK_SERIALIZER = "json"
CELERY_ACKS_LATE = True
CELERYD_PREFETCH_MULTIPLIER = 1

CELERY_RESULT_BACKEND = BROKER_URL = "redis://redis-stream:6379/0"
